version : '3.8'
services:
  litchi-nacos:
    container_name: litchi-nacos
    image: nacos/nacos-server
    build:
      context: ./nacos
    environment:
      - MODE=standalone
    volumes:
      - ./nacos/logs/:/home/nacos/logs
      - ./nacos/conf/application.properties:/home/nacos/conf/application.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    depends_on:
      - litchi-mysql
  litchi-mysql:
    container_name: litchi-mysql
    image: mysql:5.7
    build:
      context: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    command: [
          'mysqld',
          '--innodb-buffer-pool-size=80M',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci',
          '--default-time-zone=+8:00',
          '--lower-case-table-names=1'
        ]
    environment:
      MYSQL_DATABASE: 'ry-cloud'
      MYSQL_ROOT_PASSWORD: password
  litchi-redis:
    container_name: litchi-redis
    image: redis
    build:
      context: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/conf/redis.conf:/home/litchi/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /home/litchi/redis/redis.conf
  litchi-nginx:
    container_name: litchi-nginx
    image: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/html/dist:/home/litchi/projects/litchi-ui
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - litchi-gateway
    links:
      - litchi-gateway
  litchi-gateway:
    container_name: litchi-gateway
    build:
      context: ./litchi/gateway
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - litchi-redis
    links:
      - litchi-redis
  litchi-auth:
    container_name: litchi-auth
    build:
      context: ./litchi/auth
      dockerfile: dockerfile
    ports:
      - "9200:9200"
    depends_on:
      - litchi-redis
    links:
      - litchi-redis
  litchi-modules-system:
    container_name: litchi-modules-system
    build:
      context: ./litchi/modules/system
      dockerfile: dockerfile
    ports:
      - "9201:9201"
    depends_on:
      - litchi-redis
      - litchi-mysql
    links:
      - litchi-redis
      - litchi-mysql
  litchi-modules-gen:
    container_name: litchi-modules-gen
    build:
      context: ./litchi/modules/gen
      dockerfile: dockerfile
    ports:
      - "9202:9202"
    depends_on:
      - litchi-mysql
    links:
      - litchi-mysql
  litchi-modules-job:
    container_name: litchi-modules-job
    build:
      context: ./litchi/modules/job
      dockerfile: dockerfile
    ports:
      - "9203:9203"
    depends_on:
      - litchi-mysql
    links:
      - litchi-mysql
  litchi-modules-file:
    container_name: litchi-modules-file
    build:
      context: ./litchi/modules/file
      dockerfile: dockerfile
    ports:
      - "9300:9300"
    volumes:
    - ./litchi/uploadPath:/home/litchi/uploadPath
  litchi-visual-monitor:
    container_name: litchi-visual-monitor
    build:
      context: ./litchi/visual/monitor
      dockerfile: dockerfile
    ports:
      - "9100:9100"
